services:
  - type: web
    name: linkbudget
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeployTrigger: checksPass
    envVars:
      - key: PORT
        value: 8000
